added option to get decimal point in uncertainty formatted with "parenthesis" notation
r-quantities/errors pull request #60
Opened 2024-08-01 11:10 UTC by alusiani

Hi,

I propose a small unobstructive addition to the code in order to optionally get the decimal point formatted when using the "parenthesis" notation.  Example of usage:

```
format(set_errors(123.456, 12.345), notation = "parenthesis", digits=4)
## -> '123.46(1234)'
## default formatting
```

```
saved_options = options(errors.parenthesis.unc.dec.point = TRUE)
format(set_errors(123.456, 12.345), notation = "parenthesis", digits=4)
options(saved_options)
## -> '123.46(12.34)'
## optional formatting
```

2024-08-01 14:26 UTC, Enchufa2 requested changes
Great, thanks for this. I see that some of the changes that I did in the last commits have been undone for some reason. Please restore them. Comments below.

2024-08-01 14:26 UTC, Enchufa2 commented on R/print.R
> -
Please do not remove this space

2024-08-01 14:26 UTC, Enchufa2 commented on R/print.R
> -
Please do not remove this space

2024-08-01 14:26 UTC, Enchufa2 commented on R/print.R
> +  e_expon = get_exponent(e)
Please, call it `eexp` and use the `<-` operator to match the style of the rest.

2024-08-01 14:26 UTC, Enchufa2 commented on R/print.R
> +  xexp <- ifelse(.v(x)==0, e_expon+1, get_exponent(x))
Please add spaces around the operators.

2024-08-01 14:26 UTC, Enchufa2 commented on R/print.R
> +  ##+++ str(value)
Remove

2024-08-01 14:26 UTC, Enchufa2 commented on R/print.R
> +  ##+++ str(value)
Remove

2024-08-01 14:26 UTC, Enchufa2 commented on R/print.R
> -
Please restore

2024-08-01 14:26 UTC, Enchufa2 commented on tests/testthat/test-print.R
> -                 "11111.22(12)", "11111.222(12)", "11111.222220(12)", "11111.222220000(12)"))
Please restore

2024-08-01 14:26 UTC, Enchufa2 commented on tests/testthat/test-print.R
> -    paste, collapse=paste("", .pm, "")))
Please restore

2024-08-01 14:26 UTC, Enchufa2 commented on tests/testthat/test-print.R
> -    paste, collapse=paste("", .pm, "")))
Please restore

2024-08-01 14:26 UTC, Enchufa2 commented on tests/testthat/test-print.R
> -  x <- set_errors(c(0.4, NA, NaN, Inf, -Inf))
Please restore

2024-08-01 14:26 UTC, Enchufa2 commented on tests/testthat/test-print.R
> -  expect_equal(format(x, digits=2), c("0.00(10)e12", "1.00(10)e12"))
Please restore

2024-08-01 14:53 UTC, alusiani commented
Sorry for the changes, I should have checked more carefully. I was merging from an older revision I did. Part of the changes were related to using meld with omission of whitespace diffs.

I have now applied all requested changes, committed and pushed to github.  As far as I understand, that should be enough, please let me know if I also need to resubmit the pull request.

2024-08-01 18:17 UTC, Enchufa2 commented
Thanks! I renamed (and shortened) the new option, and added a new argument `decimals` to give it more visibility. I also refactored the code a little bit. Since you didn't give me push permission, I'm closing this one in favour of #61, I hope you don't mind.

2024-08-01 18:17 UTC, closed without merging

2024-08-01 20:52 UTC, alusiani commented
> Thanks! I renamed (and shortened) the new option, and added a new argument `decimals` to give it more visibility. I also refactored the code a little bit. Since you didn't give me push permission, I'm closing this one in favour of #61, I hope you don't mind.

No problem! I am not an expert of pull requests and have not realized that a push permission was asked or required.

2024-08-02 09:53 UTC, Enchufa2 commented
It is not required, but it is convenient when, like in this case, the owner of the repo wants to add some adjustments to the PR.